# Jornada820 version based on Makefile from linux 2.6.11.9
# $Id: Makefile,v 1.4 2005/07/25 09:09:14 fare Exp $
# grep for 820 for modifications.

#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SERIO)		+= serio.o
obj-$(CONFIG_SERIO_I8042)	+= i8042.o
obj-$(CONFIG_SERIO_PARKBD)	+= parkbd.o
obj-$(CONFIG_SERIO_SERPORT)	+= serport.o
obj-$(CONFIG_SERIO_CT82C710)	+= ct82c710.o
obj-$(CONFIG_SERIO_RPCKBD)	+= rpckbd.o
obj-$(CONFIG_SERIO_SA1111)	+= sa1111ps2.o
obj-$(CONFIG_SERIO_AMBAKMI)	+= ambakmi.o
obj-$(CONFIG_SERIO_Q40KBD)	+= q40kbd.o
obj-$(CONFIG_SERIO_98KBD)	+= 98kbd-io.o
obj-$(CONFIG_SERIO_GSCPS2)	+= gscps2.o
obj-$(CONFIG_SERIO_PCIPS2)	+= pcips2.o
obj-$(CONFIG_SERIO_MACEPS2)	+= maceps2.o
obj-$(CONFIG_SERIO_LIBPS2)	+= libps2.o
obj-$(CONFIG_SERIO_RAW)		+= serio_raw.o
obj-$(CONFIG_SERIO_SA1101)	+= sa1101ps2.o ### JORNADA820 modification
