#
# Makefile for the input core drivers.
#
# Jornada820 version based on Makefile 1.3 from cvs.handhelds.org
# $Id: Makefile,v 1.3 2004/07/10 22:24:10 oleg820 Exp $
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SERIO)		+= serio.o
obj-$(CONFIG_SERIO_I8042)	+= i8042.o
obj-$(CONFIG_SERIO_PARKBD)	+= parkbd.o
obj-$(CONFIG_SERIO_SERPORT)	+= serport.o
obj-$(CONFIG_SERIO_CT82C710)	+= ct82c710.o
obj-$(CONFIG_SERIO_RPCKBD)	+= rpckbd.o
obj-$(CONFIG_SERIO_CLPS7500)	+= clps7500ps2.o
obj-$(CONFIG_SERIO_SA1111)	+= sa1111ps2.o
obj-$(CONFIG_SERIO_AMBAKMI)	+= ambakmi.o
obj-$(CONFIG_SERIO_Q40KBD)	+= q40kbd.o
obj-$(CONFIG_SERIO_98KBD)	+= 98kbd-io.o
obj-$(CONFIG_SERIO_GSCPS2)	+= gscps2.o
obj-$(CONFIG_SERIO_PCIPS2)	+= pcips2.o
obj-$(CONFIG_SERIO_MACEPS2)	+= maceps2.o
obj-$(CONFIG_SERIO_SA1101)	+= sa1101ps2.o
