#!/bin/sh
# $Id: functions,v 1.9 2004/05/02 11:01:54 fare Exp $
# Shell functions to ease your life at the initrd debug command prompt
# Use the shell script /etc/please

ascii_table () {
  i=32 ; while [ $i -lt 256 ] ; do
    case $i in
      ?|[12][0-9]|3[01]|127|155) j=" " ;;
      *) j=$(eval "echo -ne '\\$(printf %03o $i)'") ;;
    esac
    printf "%02x:%c " "$i" "$j"
    i=$(($i+1))
    #if [ $(($i % 16)) = 0 ] ; then echo ; fi 
  done
}

re () {
  # RE-REad RenE's Runtime-Environment
  . /etc/functions
  [ -f /mnt/linux/functions ] && . /mnt/linux/functions
}

mcs () {
  # my console settings: visible cursor, latin1 encoding, normal colors, bold.
  echo -ne '\033[?2c\033(?B\033[m\033[1m' # ]])]
}
mcsv () { # my console settings for vt #n
  mcs > /dev/vc/${1:-1}
}

latin () { # ???
  # See /usr/src/linux/Documentation/unicode.txt
  # magic letter: B (latin1) 0 (DEC VT100 gfx) U (ibm cp437) K (user defined)
  # for some reason, this puts the terminal in black on black, so we reset it.
  echo -ne "\\033(?${1:-B}\\033[m"
}
cursor () {
  # See http://www.linux.org/docs/ldp/howto/Framebuffer-HOWTO-5.html#ss5.9
  echo -ne "\\033[?${1:-2}c"
}

nbdswap () {
  # See http://www.it.uc3m.es/~ptb/nbd/
  mknod /dev/nb0 b 43 0
  nbd-client 192.168.0.3 665 /dev/nb0 -swap
  swapon /dev/nb0
  : nbd-client -d /dev/nb0
}

link_applets () {
  rm -f /linuxrc
  /bin/busybox --install -s
  ln -s ../etc/please /bin/please
}

ensure_tmp () {
  mkdir -p tmp
  CHECK '[ -d tmp ]' \
      '' \
      "Cannot ensure existence of $PWD/tmp directory."
}

ensure_proc () {
CHECK '[ -d proc ]' \
      'mkdir proc' \
      "Cannot make a $PWD/proc directory node."
CHECK '[ -f proc/cpuinfo ]' \
      'mount proc proc -t proc' \
      "Cannot mount the $PWD/proc partition."
}

ensure_dev () {
CHECK '[ -d dev ]' \
      'mkdir dev' \
      "Cannot make a $PWD/dev directory node."
CHECK '[ -c dev/console ]' \
      'mount devfs dev -t devfs' \
      "Cannot mount the $PWD/dev partition."
}

my_linuxrc () {
  echo "We're in my_linuxrc! PID=$$" >> /tmp/log 
  ps >> /tmp/log

  cd /
  mkdir -p /tmp
  LOG "Mounting proc and dev"
  ensure_proc
  ensure_dev

  # make symlinks for all those busybox applications
  LOG "Linking busybox applets"
  link_applets

  # Fallback plan: busybox's linuxrc
  ABORT () {
    if [ -n "$1" ] ; then
      LOG "$1"
    fi
    LOG "Fallback plan: running busybox on the initial ramdisk."
    sysinit
    LOGC "This is a single-user shell with PID=$$.
You can attempt to pivot_root manually, or
you can instead let busybox manage your consoles with 'exec /linuxrc'"
    exec /bin/sh < dev/console > dev/console 2>&1
  }

  try_pivot_root

  ABORT "Abnormal return from try_pivot_root."

}

lisp () {
  clisp -E iso-8859-1 -repl -ansi /mnt/linux/foo.lisp $@
}

linkme () {
  cd /mnt/linux
  for i in etc/* usr/* lib/* ; do
    [ -e /$i ] || ln -s /mnt/linux/$i /$i
  done
  for i in bin/* ; do
    ln -s /mnt/linux/$i /usr/bin/
  done
}

net0 () {
  hostname mildendo
  ifconfig eth0 192.168.0.16 netmask 255.255.255.0 broadcast 192.168.0.255
  route add default gw 192.168.0.1
  rdate 192.168.0.3
  export DISTCC_HOSTS=192.168.0.3 CC="distcc arm-linux-gcc" CFLAGS="-Os -fomit-frame-pointer"
}
net0a () {
  hostname mildendo
  ifconfig eth0 10.31.0.16 netmask 255.255.255.0 broadcast 10.31.0.255
  route add default gw 10.31.0.1
  rdate 10.31.0.1
  export DISTCC_HOSTS=10.31.0.1 CC="distcc arm-linux-gcc" CFLAGS="-Os -fomit-frame-pointer"
}

udhcp () {
  # http://udhcp.busybox.net/README.udhcpc
  DEVICE=${1:-eth0}
  ifconfig $DEVICE > /dev/urandom
  udhcpc -H mildendo -n -f -q -s /etc/udhcpc.sh -i $DEVICE
}

change_root () {
  # See /usr/src/linux/Documentation/initrd.txt
  PARTNUM=${1:-3} # Partition with root disk in /dev/hda. Default: hda3
  : cardmgr -o
  # /dev/hda1 = 0x301, /dev/hda2 = 0x302, etc
  echo $(( 768 + $PARTNUM )) > /proc/sys/kernel/real-root-dev
  #cat /proc/sys/kernel/real-root-dev
  #cat /proc/cmdline
}

ABORT () {
  if [ -n "$1" ] ; then
    LOG "$1"
  fi
  exit ${2:-42}
}
CHECK () {
  # Check whether what we want is OK
  ERR="${3:-Something is wrong about the target filesystem.}
Stopping before we do a big mistake."
  LOGT -n "Checking: $1 ... "
  if eval "$1" ; then
    LOGT "ok"
  else
    if [ -n "$2" ] ; then
      LOGT "failed. Taking a corrective measure: $2"
      eval "$2"
      eval "$1" ||
      ABORT "$ERR" ${4:-42}
    else
      ABORT "$ERR" ${4:-42}
    fi
  fi
}

no_noautomount_p () {
  # create a file or directory noautomount on your WinCE FAT partition
  # to prevent the boot disk image from automounting your rootfs.
  R=0
  [ -d /mnt/dos ] || mkdir -p /mnt/dos
  DOSPART=$(fdisk -l /dev/hda | grep FAT | head -1 | cut -d" " -f1 )
  if [ -n "$DOSPART" ] ; then
    mount $DOSPART /mnt/dos -t vfat -o ro
    if [ -e /mnt/dos/noautomount ] ; then
      R=1
    fi
    umount /mnt/dos
  fi
  return $R
}

ensure_no_noautomount () {
  # Remove any noautomount flag
  [ -d /mnt/dos ] || mkdir -p /mnt/dos
  DOSPART=$(fdisk -l /dev/hda | grep FAT | head -1 | cut -d" " -f1 )
  if [ -n "$DOSPART" ] ; then
    mount $DOSPART /mnt/dos -t vfat -o rw,noatime
    [ -d /mnt/dos/noautomount ] && rmdir /mnt/dos/noautomount
    [ -f /mnt/dos/noautomount ] && rm -f /mnt/dos/noautomount
    umount /mnt/dos
  fi
}

ensure_linuxpartition () {
  PART=$(fdisk -l /dev/hda | grep '83  Linux' | head -1 | cut -d" " -f1 )
  [ -n "$PART" ] ||
  ABORT "Cannot find a Linux partition. Please make one with fdisk."
  CHECK '[ -d /mnt/linux ]' \
	'mkdir -p /mnt/linux' \
	'Cannot make /mnt/linux directory.'
  CHECK "grep -q '$PART /mnt/linux' /proc/mounts" \
	"mount $PART /mnt/linux -o noatime,rw" \
	"Cannot mount the target partition $PART to /mnt/linux."
  PARTNUM="$(echo $PART | cut -c9-)"
  change_root $PARTNUM # necessary if we're not PID=1
}
has_init_p () {
  # [ -x linuxrc ] ||
  [ -x sbin/init ] || [ -x etc/init ] || [ -x bin/init ] ||
  [ -x bin/sh ]
}
do_init () {
  # [ -x linuxrc ] && exec ./linuxrc
  if [ 1 = "$$" ] ; then
    [ -x sbin/init ] && exec ./sbin/init
    [ -x etc/init ] && exec ./etc/init
    [ -x bin/init ] && exec ./bin/init
  else
    LOG "PID=$$, not 1, so let's not try to exec init."
  fi
  [ -x bin/sh ] && exec ./bin/sh
}

ensure_partition_bootable () {
  for i in bin sbin usr/bin usr/sbin etc etc/pcmcia \
	   tmp var/run initrd lib/modules mnt ; do
    CHECK "[ -d $i ]" "mkdir -p $i" \
	"Cannot ensure directory /$i on target partition"
  done
  for i in bin/busybox bin/cardmgr bin/cardctl \
	etc/functions etc/please etc/udhcpc.sh \
	etc/passwd etc/group etc/fstab etc/inittab \
	etc/host.conf etc/nsswitch.conf etc/resolv.conf \
	etc/pcmcia/shared etc/pcmcia/config etc/pcmcia/config.opts \
	etc/pcmcia/ide etc/pcmcia/ide.opts \
	etc/pcmcia/network etc/pcmcia/network.opts
  do
    CHECK "[ -f $i ]" \
	"cp -a /$i $i" \
	"Cannot ensure /$i on target partition."
  done
  CHECK "grep -q pivot_root_part2 etc/functions" \
	"cp -af /etc/functions etc/functions" \
	"Cannot ensure pivot_root_part2 in target /etc/functions"
  LOGT "Ensuring a working bin/sh..."
  CHECK "[ -x bin/sh ]" \
	"chroot . /bin/busybox --install -s" \
	"Cannot ensure a working /bin/sh on target."
  LOGT "Installing kernel modules..."
  MODULES="lib/modules/$(uname -r)"
  CHECK "[ -d $MODULES ]" "cp -a /$MODULES $MODULES" \
	"Cannot ensure kernel modules on target partition"
}

LOGT () {
  opts=""
  case "$1" in
    -*) opts="$1" ; shift ;;
  esac
  echo $opts "$$ $(date +'%Y-%m-%d %H:%M:%S'): $@" >> /tmp/log
}
LOGC () {
  echo "$@" >&2
}
LOG () {
  LOGT "$@" ; LOGC "$@"
}

try_pivot_root () {
  # NB: So as to be able to free the ramdisk's memory,
  # this script must be run as the only process, #1,
  # either from linuxrc of from a single-user mode shell.

  LOG "Let's pivot_root if we can."
  cd /
  ensure_tmp ; ensure_proc ; ensure_dev # necessary for many things
  LOG "Checking for a CF memory card..."
  CHECK 'dd if=/dev/hda count=1 of=/dev/null 2> /dev/null' \
	'cardmgr -o ; sleep 1' \
	"Cannot find a CF disk."
  LOG "Checking for noautomount request..."
  CHECK no_noautomount_p '' \
	"User requested noautomount - not trying to mount a Linux partition."
  LOG "Trying to mount a Linux partition..."
  ensure_linuxpartition
  LOG "Trying to make the Linux partition livable..."
  cd /mnt/linux
  LOG "Ensuring the target partition is bootable..."
  ensure_partition_bootable

  if [ 1 = $$ ] ; then
    ensure_proc
    ensure_dev
    LOG "Changing current I/O to new /dev"
    exec < dev/console > dev/console 2>&1
    LOG "Switching root partition..."
    cp /tmp/log tmp/log # copying logfile over...
    pivot_root . initrd
    exec chroot . ./bin/sh ./etc/please pivot_root_part2 \
	< dev/console > dev/console 2>&1
  else
    cd /
    umount /mnt/linux
    LOG "PID = $$ != 1; Let's trust linux/init/do_mount.c for the sequel ..."
    exit 0
  fi
}

pivot_root_part2 () {
  LOG "Made it to the other side!"
  LOG "Ensuring dev and proc"
  ensure_dev ; ensure_proc
  LOG "Cleaning filedescriptors"
  cd /
  exec < dev/console > dev/console 2>&1
  LOGT "mounts:
$(cat proc/mounts)"
  LOGT "ps:
$(ps)"
  LOG "Unmounting dev and proc from initrd"
  umount initrd/dev
  umount initrd/proc
  LOG "Freeing resources occupied by the initrd..."
  umount initrd
  # problem: blockdev (part of the util-linux debian package) isn't in busybox
  blockdev --flushbufs /dev/rd/0 # /dev/ram0
  if [ 1 = $$ ] ; then
    LOG "Jumping into the rootfs' init process..."
    do_init
  else
    LOG "PID = $$ != 1; Let's trust linux/init/do_mount.c for the sequel ..."
    exit 0
  fi
}

sysinit () {
  # replaces the /etc/init.d/rcS script -- see /etc/inittab
  echo -ne '\033[?2c\033(?B\033[m\033[1m'
  echo -e 'Welcome to Linux for the HP Jornada 820.\033[m'
}
