#
# Makefile for the linux kernel.
#
# Jornada820 version based on Makefile 1.4 from cvs.handhelds.org
# $Id: Makefile,v 1.1 2004/07/03 13:26:15 fare Exp $


obj-y				+= platform.o
obj-$(CONFIG_ARM_AMBA)		+= amba.o
obj-$(CONFIG_ICST525)		+= icst525.o
obj-$(CONFIG_SA1101)		+= sa1101.o
obj-$(CONFIG_SA1111)		+= sa1111.o
obj-$(CONFIG_PCI_HOST_PLX90X0)	+= plx90x0.o
obj-$(CONFIG_PCI_HOST_VIA82C505) += via82c505.o
obj-$(CONFIG_DMABOUNCE)		+= dmabounce.o
obj-$(CONFIG_IPAQ_HANDHELD)     += ipaq/
