# Makefile.project
# You specify target name, source files, flags for compiling/building here


TARGETBIN = j820boot.exe

# TODO: I had to make sure all sources are at the current directory, fix this
# in the future maybe.
# (You may want to symlink asmstuff.asm and asm.asm)

SRCS = \
    gpio.c	    	\
    memory.c	    	\
    uart.c	    	\
    boot.c	    	\
    asmstuff.S	\
    asm.S		\

