#
# Makefile for the input core drivers.
#
# Jornada820 version based on Makefile 1.2 from cvs.handhelds.org
# $Id: Makefile,v 1.1 2004/06/30 14:03:12 fare Exp $
#

# Each configuration option enables a list of files.

obj-$(CONFIG_KEYBOARD_ATKBD)		+= atkbd.o
obj-$(CONFIG_KEYBOARD_MAPLE)		+= maple_keyb.o
obj-$(CONFIG_KEYBOARD_SUNKBD)		+= sunkbd.o
obj-$(CONFIG_KEYBOARD_LKKBD)		+= lkkbd.o
obj-$(CONFIG_KEYBOARD_XTKBD)		+= xtkbd.o
obj-$(CONFIG_KEYBOARD_AMIGA)		+= amikbd.o
obj-$(CONFIG_KEYBOARD_NEWTON)		+= newtonkbd.o
obj-$(CONFIG_KEYBOARD_98KBD)		+= 98kbd.o
obj-$(CONFIG_SA1100_JORNADA820)		+= j820_keyb.o
