#!/bin/busybox sh
# This file gets clobbered and replaced by a symlink to busybox at startup.
# We must run busybox manually because
# symlinks are not installed at boot due to a limitation of debugfs,
# and we hate hardlinks due to a limitation in busybox's du.
echo "We're in linuxrc! PID=$$" >> /tmp/log
ps >> /tmp/log
. /etc/functions
my_linuxrc
#exec /bin/busybox sh /etc/please my_linuxrc $@
